"use client";

import { useEffect, useState } from "react";
import { AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { UploadDropzone } from "@/components/demo/UploadDropzone";
import { ExampleImages } from "@/components/demo/ExampleImages";
import { ResultsPanel } from "@/components/demo/ResultsPanel";
import { predictImage, ApiError, type PredictionResponse } from "@/lib/api";

type Status = "idle" | "loading" | "done" | "error";

export function DemoPanel() {
  const [file, setFile] = useState<File | Blob | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [status, setStatus] = useState<Status>("idle");
  const [result, setResult] = useState<PredictionResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
    };
  }, [previewUrl]);

  const reset = () => {
    setFile(null);
    setPreviewUrl(null);
    setStatus("idle");
    setResult(null);
    setError(null);
  };

  const selectFile = (f: File | Blob) => {
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    setFile(f);
    setPreviewUrl(URL.createObjectURL(f));
    setStatus("idle");
    setResult(null);
    setError(null);
  };

  const pickExample = async (url: string) => {
    const res = await fetch(url);
    const blob = await res.blob();
    selectFile(blob);
  };

  const analyze = async () => {
    if (!file) return;
    setStatus("loading");
    setError(null);
    try {
      const res = await predictImage(file);
      setResult(res);
      setStatus("done");
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Unexpected error running inference.");
      setStatus("error");
    }
  };

  return (
    <div>
      <div className="mb-8 flex items-start gap-3 rounded-2xl border border-amber/25 bg-amber/[0.06] p-4">
        <AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber" />
        <p className="text-xs leading-relaxed text-muted">
          <span className="font-medium text-foreground">Research prototype — not a certified diagnostic device.</span>{" "}
          Predictions are generated by the exact ResNet-50 + SWIN-B ensemble from the paper for
          demonstration purposes only, and must never be used for real clinical decisions.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div>
          <UploadDropzone
            file={file}
            previewUrl={previewUrl}
            onSelect={selectFile}
            onClear={reset}
            disabled={status === "loading"}
          />

          {!file && (
            <div className="mt-6">
              <ExampleImages onPick={(url) => pickExample(url)} disabled={status === "loading"} />
            </div>
          )}

          {file && status !== "loading" && (
            <div className="mt-6 flex gap-3">
              <Button onClick={analyze} size="lg" className="flex-1">
                {status === "error" ? "Retry analysis" : "Analyze image"}
              </Button>
            </div>
          )}
        </div>

        <ResultsPanel status={status} result={result} error={error} onReset={reset} />
      </div>
    </div>
  );
}
